import type {Metadata} from "next";
import '@gravity-ui/uikit/styles/fonts.css';
import '@gravity-ui/uikit/styles/styles.css';
import '@/app-fsd/styles/theme.scss'
import {GravityThemeProvider} from "@/app-fsd/providers/gravityThemeProvider/ui/GravityThemeProvider";
import {MyApolloProvider} from "@/app-fsd/providers/apolloProvider/ui/MyApolloProvider";
import {MyToasterProvider} from "@/app-fsd/providers/toasterProvider/ui/MyToasterProvider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (

        <html lang="en">
        <GravityThemeProvider>
            <body cz-shortcut-listen="true">
            <MyToasterProvider>
                <MyApolloProvider>
                    {children}
                </MyApolloProvider>
            </MyToasterProvider>
            </body>
        </GravityThemeProvider>
        </html>
    );
}
